---
title: "Residual Plots"
---

```{r, message=FALSE, warning=FALSE, include=FALSE}

# load packages used

library(readxl)
library(tidyverse)
library(glmnet)
library(randomForest)
library(caret)
library(car)
library(knitr)
library(patchwork)
library(leaps)

# load data
od_data = read_excel("overdose_data.xlsx")

# change state and year to factor variables
od_data = od_data %>%
  mutate(
    state = factor(state),
    year = factor(year),
    med_income = med_income/1000
  )

# change all 9999 values to NA
od_data = od_data %>%
  mutate(across(where(is.numeric), ~ na_if(., 9999)))


```

## All Drugs

```{r, include=FALSE}

data_bach = od_data %>%
  select(alldrug_rate, med_income, poverty, bachelors) %>%
  drop_na()

x = model.matrix(alldrug_rate ~ med_income + poverty + bachelors,
                 data = data_bach)[, -1]

y = data_bach$alldrug_rate

set.seed(1)

# 10-fold cross-validation ridge regression
cv.out.ridge = cv.glmnet(x, y, alpha = 0, nfolds = 10)

# best lambda
bestlam.ridge = cv.out.ridge$lambda.min

# final ridge model
ridge.mod = glmnet(x, y, alpha = 0, lambda = bestlam.ridge)

# coefficients
coef(ridge.mod)

# predictions using 10-fold CV-selected lambda
ridge.pred.alldrug = predict(cv.out.ridge, s = "lambda.min", newx = x)

actual.alldrug = y

# MSE, RMSE, MAE
alldrug_bach.ridge.mse = mean((actual.alldrug - ridge.pred.alldrug)^2)
alldrug_bach.ridge.rmse = sqrt(alldrug_bach.ridge.mse)
alldrug_bach.ridge.mae = mean(abs(actual.alldrug - ridge.pred.alldrug))

# R-squared
alldrug_bach.ridge.r2 = 1 - sum((actual.alldrug - ridge.pred.alldrug)^2) /
  sum((actual.alldrug - mean(actual.alldrug))^2)

# Adjusted R-squared
n = length(actual.alldrug)
p = ncol(x)

alldrug_bach.ridge.adjr2 = 1 - ((1 - alldrug_bach.ridge.r2) * (n - 1)) /
  (n - p - 1)

```

```{r, message=FALSE, warning=FALSE, echo=FALSE}

# Residuals
res_alldrug = actual.alldrug - as.vector(ridge.pred.alldrug)

plot(ridge.pred.alldrug, res_alldrug,
     xlab = "Fitted Values",
     ylab = "Residuals",
     main = "Residual Plot: All Drugs Model")
abline(h = 0,
       col = "red",
       lwd = 2)


qqnorm(res_alldrug,
       main = "QQ Plot: All Drugs Model")
qqline(res_alldrug,
       col = "red",
       lwd = 2)

```

## Heroin

```{r, include=FALSE}

data_hs = od_data %>%
  select(heroin_rate, med_income, poverty, hs_grad) %>%
  drop_na()

x = model.matrix(heroin_rate ~ med_income + poverty + hs_grad,
                 data = data_hs)[, -1]

y = data_hs$heroin_rate

set.seed(1)

# 10-fold cross-validation ridge regression
cv.out.ridge = cv.glmnet(x, y, alpha = 0, nfolds = 10)

# best lambda
bestlam.ridge = cv.out.ridge$lambda.min

# final ridge model
ridge.mod = glmnet(x, y, alpha = 0, lambda = bestlam.ridge)

# coefficients
coef(ridge.mod)

# predictions using 10-fold CV-selected lambda
ridge.pred.heroin = predict(cv.out.ridge, s = "lambda.min", newx = x)

actual.heroin = y

# MSE, RMSE, MAE
heroin_hs.ridge.mse = mean((actual.heroin - ridge.pred.heroin)^2)
heroin_hs.ridge.rmse = sqrt(heroin_hs.ridge.mse)
heroin_hs.ridge.mae = mean(abs(actual.heroin - ridge.pred.heroin))

# R-squared
heroin_hs.ridge.r2 = 1 - sum((actual.heroin - ridge.pred.heroin)^2) /
  sum((actual.heroin - mean(actual.heroin))^2)

# Adjusted R-squared
n = length(actual.heroin)
p = ncol(x)

heroin_hs.ridge.adjr2 = 1 - ((1 - heroin_hs.ridge.r2) * (n - 1)) /
  (n - p - 1)

```

```{r, message=FALSE, warning=FALSE, echo=FALSE}

# Residuals
res_heroin = actual.heroin - as.vector(ridge.pred.heroin)

plot(ridge.pred.heroin, res_heroin,
     xlab = "Fitted Values",
     ylab = "Residuals",
     main = "Residual Plot: Heroin Model")
abline(h = 0,
       col = "red",
       lwd = 2)


qqnorm(res_heroin,
       main = "QQ Plot: Heroin Model")
qqline(res_heroin,
       col = "red",
       lwd = 2)

```

## Prescription Opioids

```{r, include=FALSE}

data_bach = od_data %>%
  select(rxopioids_rate, med_income, poverty, bachelors) %>%
  drop_na()

#backward elimination
#regfit_bach = regsubsets(rxopioids_rate ~ med_income + poverty + bachelors, 
#                         data = data_bach, 
#                         method = "backward")

# backward elimination using 10-fold cross validation
k = 10
set.seed(1)

folds = sample(1:k, nrow(data_bach), replace = TRUE)

cv.errors = matrix(NA, k, 3, dimnames = list(NULL, paste(1:3)))

# function for prediction with regsubsets
predict.regsubsets = function(object, newdata, id, ...){
  form = as.formula(object$call[[2]])
  mat = model.matrix(form, newdata)
  coefi = coef(object, id = id)
  xvars = names(coefi)
  mat[, xvars] %*% coefi
}

for(j in 1:k){
  best.fit = regsubsets(rxopioids_rate ~ med_income + poverty + bachelors, 
                        data = data_bach[folds != j, ],
                        nvmax = 3,
                        method = "backward")
  
  for(i in 1:3){
    pred = predict(best.fit, data_bach[folds == j, ], id = i)
    cv.errors[j, i] = mean((data_bach$rxopioids_rate[folds == j] - pred)^2)
  }
}

mean.cv.errors = apply(cv.errors, 2, mean)

plot(mean.cv.errors, type = "b")

# perform best subset selection and obtain the model
reg.best = regsubsets(rxopioids_rate ~ med_income + poverty + bachelors, 
                      data = data_bach, nvmax = 3, method = "backward")
coef(reg.best, which.min(mean.cv.errors))


# obtained model
rxopioids_model_bach = lm(rxopioids_rate ~ poverty + bachelors, 
                       data = data_bach)


summary(rxopioids_model_bach)


# Test MSE, RMSE, MAE
cv.mae = rep(NA, k)

for(j in 1:k){
  fit = lm(rxopioids_rate ~ poverty + bachelors,
           data = data_bach[folds != j, ])
  
  pred = predict(fit, newdata = data_bach[folds == j, ])
  
  actual = data_bach$rxopioids_rate[folds == j]
  
  cv.mae[j] = mean(abs(actual - pred))
}

rxopioids_bach.mse = min(mean.cv.errors)
rxopioids_bach.rmse = sqrt(rxopioids_bach.mse)
rxopioids_bach.mae = mean(cv.mae)
rxopioids_bach.adjr2 = summary(rxopioids_model_bach)$adj.r.squared

```

```{r, message=FALSE, warning=FALSE, echo=FALSE}

# Residuals
res_rxopioids = resid(rxopioids_model_bach) 

plot(predict(rxopioids_model_bach), res_rxopioids, 
     xlab = "Fitted Values", 
     ylab = "Residuals", 
     main = "Residual Plot: Prescription Opioids Model") 
abline(h=0)


qqnorm(res_rxopioids,
       main = "QQ Plot: Prescription Opioids Model")
qqline(res_rxopioids, col = "red")

```

## Cocaine

```{r, include=FALSE}

# data cleaning
data_bach = od_data %>%
  select(cocaine_rate, med_income, poverty, bachelors) %>%
  drop_na()

#backward elimination
#regfit_bach = regsubsets(cocaine_rate ~ med_income + poverty + bachelors, 
#                         data = data_bach, 
#                         method = "backward")

# backward elimination using 10-fold cross validation
k = 10
set.seed(1)

folds = sample(1:k, nrow(data_bach), replace = TRUE)

cv.errors = matrix(NA, k, 3, dimnames = list(NULL, paste(1:3)))

# function for prediction with regsubsets
predict.regsubsets = function(object, newdata, id, ...){
  form = as.formula(object$call[[2]])
  mat = model.matrix(form, newdata)
  coefi = coef(object, id = id)
  xvars = names(coefi)
  mat[, xvars] %*% coefi
}

for(j in 1:k){
  best.fit = regsubsets(cocaine_rate ~ med_income + poverty + bachelors, 
                        data = data_bach[folds != j, ],
                        nvmax = 3,
                        method = "backward")
  
  for(i in 1:3){
    pred = predict(best.fit, data_bach[folds == j, ], id = i)
    cv.errors[j, i] = mean((data_bach$cocaine_rate[folds == j] - pred)^2)
  }
}

mean.cv.errors = apply(cv.errors, 2, mean)

plot(mean.cv.errors, type = "b")

# perform best subset selection and obtain the model
reg.best = regsubsets(cocaine_rate ~ med_income + poverty + bachelors, 
                      data = data_bach, nvmax = 3, method = "backward")
coef(reg.best, which.min(mean.cv.errors))


# obtained model
cocaine_model_bach = lm(cocaine_rate ~ med_income + bachelors, 
                       data = data_bach)


summary(cocaine_model_bach)


# Test MSE, RMSE, MAE
cv.mae = rep(NA, k)

for(j in 1:k){
  fit = lm(cocaine_rate ~ med_income + bachelors,
           data = data_bach[folds != j, ])
  
  pred = predict(fit, newdata = data_bach[folds == j, ])
  
  actual = data_bach$cocaine_rate[folds == j]
  
  cv.mae[j] = mean(abs(actual - pred))
}

cocaine_bach.mse = min(mean.cv.errors)
cocaine_bach.rmse = sqrt(cocaine_bach.mse)
cocaine_bach.mae = mean(cv.mae)
cocaine_bach.adjr2 = summary(cocaine_model_bach)$adj.r.squared

```

```{r, message=FALSE, warning=FALSE, echo=FALSE}

# Residuals
res_cocaine = resid(cocaine_model_bach) 

plot(predict(cocaine_model_bach), res_cocaine, 
     xlab = "Fitted Values", 
     ylab = "Residuals", 
     main = "Residual Plot: Cocaine Model") 
abline(h=0)


qqnorm(res_cocaine,
       main = "QQ Plot: Cocaine Model")
qqline(res_cocaine, col = "red")

```

## Methamphetamine

```{r, include=FALSE}

data_bach = od_data %>%
  select(meth_rate, med_income, poverty, bachelors) %>%
  drop_na()


x = model.matrix(meth_rate ~ med_income + poverty + bachelors,
                 data = data_bach)[, -1]

y = data_bach$meth_rate

set.seed(1)

# 10-fold cross-validation ridge regression
cv.out.ridge = cv.glmnet(x, y, alpha = 0, nfolds = 10)

# best lambda
bestlam.ridge = cv.out.ridge$lambda.min

# final ridge model
ridge.mod = glmnet(x, y, alpha = 0, lambda = bestlam.ridge)

# coefficients
coef(ridge.mod)

# predictions using 10-fold CV-selected lambda
ridge.pred.meth = predict(cv.out.ridge, s = "lambda.min", newx = x)

actual.meth = y

# MSE, RMSE, MAE
meth_bach.ridge.mse = mean((actual.meth - ridge.pred.meth)^2)
meth_bach.ridge.rmse = sqrt(meth_bach.ridge.mse)
meth_bach.ridge.mae = mean(abs(actual.meth - ridge.pred.meth))

# R-squared
meth_bach.ridge.r2 = 1 - sum((actual.meth - ridge.pred.meth)^2) /
  sum((actual.meth - mean(actual.meth))^2)

# Adjusted R-squared
n = length(actual.meth)
p = ncol(x)

meth_bach.ridge.adjr2 = 1 - ((1 - meth_bach.ridge.r2) * (n - 1)) /
  (n - p - 1)


```

```{r, message=FALSE, warning=FALSE, echo=FALSE}

# Residuals
res_meth = actual.meth - as.vector(ridge.pred.meth)

plot(ridge.pred.meth, res_meth,
     xlab = "Fitted Values",
     ylab = "Residuals",
     main = "Residual Plot: Methamphetamine Model")
abline(h = 0,
       col = "red",
       lwd = 2)


qqnorm(res_meth,
       main = "QQ Plot: Methamphetamine Model")
qqline(res_meth,
       col = "red",
       lwd = 2)

```

## Benzodiazepines

```{r, include=FALSE}

data_hs = od_data %>%
  select(benzodiazepines_rate, med_income, poverty, hs_grad) %>%
  drop_na()

#backward elimination
#regfit_hs = regsubsets(benzodiazepines_rate ~ med_income + poverty + hs_grad, 
#                       data = data_hs, method = "backward")


# backward elimination using 10-fold cross validation
k = 10
set.seed(1)

folds = sample(1:k, nrow(data_hs), replace = TRUE)

cv.errors = matrix(NA, k, 3, dimnames = list(NULL, paste(1:3)))

# function for prediction with regsubsets
predict.regsubsets = function(object, newdata, id, ...){
  form = as.formula(object$call[[2]])
  mat = model.matrix(form, newdata)
  coefi = coef(object, id = id)
  xvars = names(coefi)
  mat[, xvars] %*% coefi
}

for(j in 1:k){
  best.fit = regsubsets(benzodiazepines_rate ~ med_income + poverty + hs_grad, 
                        data = data_hs[folds != j, ],
                        nvmax = 3,
                        method = "backward")
  
  for(i in 1:3){
    pred = predict(best.fit, data_hs[folds == j, ], id = i)
    cv.errors[j, i] = mean((data_hs$benzodiazepines_rate[folds == j] - pred)^2)
  }
}

mean.cv.errors = apply(cv.errors, 2, mean)

plot(mean.cv.errors, type = "b")

# perform best subset selection and obtain the model
reg.best_hs = regsubsets(benzodiazepines_rate ~ med_income + poverty + hs_grad, 
                         data = data_hs, nvmax = 3, method = "backward")
coef(reg.best_hs, which.min(mean.cv.errors))


# obtained model
benzo_model_hs = lm(benzodiazepines_rate ~ poverty, 
                     data = data_hs)

summary(benzo_model_hs)


# Test MSE, RMSE, MAE
cv.mae = rep(NA, k)

for(j in 1:k){
  fit = lm(benzodiazepines_rate ~ poverty,
           data = data_hs[folds != j, ])
  
  pred = predict(fit, newdata = data_hs[folds == j, ])
  
  actual = data_hs$benzodiazepines_rate[folds == j]
  
  cv.mae[j] = mean(abs(actual - pred))
}

benzo_hs.mse = min(mean.cv.errors)
benzo_hs.rmse = sqrt(benzo_hs.mse)
benzo_hs.mae = mean(cv.mae)
benzo_hs.adjr2 = summary(benzo_model_hs)$adj.r.squared

```

```{r, message=FALSE, warning=FALSE, echo=FALSE}

# Residuals
res_benzo = resid(benzo_model_hs) 

plot(predict(benzo_model_hs), res_benzo, 
     xlab = "Fitted Values", 
     ylab = "Residuals", 
     main = "Residual Plot: Benzodiazepines Model") 
abline(h=0)

qqnorm(res_benzo,
       main = "QQ Plot: Benzodiazepines Model")
qqline(res_benzo, col = "red")

```
